/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TrackingInformationService } from "../trackingInformation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TrackingInformationCreateInput } from "./TrackingInformationCreateInput";
import { TrackingInformation } from "./TrackingInformation";
import { TrackingInformationFindManyArgs } from "./TrackingInformationFindManyArgs";
import { TrackingInformationWhereUniqueInput } from "./TrackingInformationWhereUniqueInput";
import { TrackingInformationUpdateInput } from "./TrackingInformationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TrackingInformationControllerBase {
  constructor(
    protected readonly service: TrackingInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TrackingInformation })
  @nestAccessControl.UseRoles({
    resource: "TrackingInformation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTrackingInformation(
    @common.Body() data: TrackingInformationCreateInput
  ): Promise<TrackingInformation> {
    return await this.service.createTrackingInformation({
      data: data,
      select: {
        consignmentId: true,
        createdAt: true,
        id: true,
        jobId: true,
        latitude: true,
        longitude: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TrackingInformation] })
  @ApiNestedQuery(TrackingInformationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TrackingInformation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trackingInformations(
    @common.Req() request: Request
  ): Promise<TrackingInformation[]> {
    const args = plainToClass(TrackingInformationFindManyArgs, request.query);
    return this.service.trackingInformations({
      ...args,
      select: {
        consignmentId: true,
        createdAt: true,
        id: true,
        jobId: true,
        latitude: true,
        longitude: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TrackingInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrackingInformation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trackingInformation(
    @common.Param() params: TrackingInformationWhereUniqueInput
  ): Promise<TrackingInformation | null> {
    const result = await this.service.trackingInformation({
      where: params,
      select: {
        consignmentId: true,
        createdAt: true,
        id: true,
        jobId: true,
        latitude: true,
        longitude: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TrackingInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrackingInformation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTrackingInformation(
    @common.Param() params: TrackingInformationWhereUniqueInput,
    @common.Body() data: TrackingInformationUpdateInput
  ): Promise<TrackingInformation | null> {
    try {
      return await this.service.updateTrackingInformation({
        where: params,
        data: data,
        select: {
          consignmentId: true,
          createdAt: true,
          id: true,
          jobId: true,
          latitude: true,
          longitude: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TrackingInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrackingInformation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTrackingInformation(
    @common.Param() params: TrackingInformationWhereUniqueInput
  ): Promise<TrackingInformation | null> {
    try {
      return await this.service.deleteTrackingInformation({
        where: params,
        select: {
          consignmentId: true,
          createdAt: true,
          id: true,
          jobId: true,
          latitude: true,
          longitude: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
