/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ConsignmentService } from "../consignment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ConsignmentCreateInput } from "./ConsignmentCreateInput";
import { Consignment } from "./Consignment";
import { ConsignmentFindManyArgs } from "./ConsignmentFindManyArgs";
import { ConsignmentWhereUniqueInput } from "./ConsignmentWhereUniqueInput";
import { ConsignmentUpdateInput } from "./ConsignmentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ConsignmentControllerBase {
  constructor(
    protected readonly service: ConsignmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Consignment })
  @nestAccessControl.UseRoles({
    resource: "Consignment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createConsignment(
    @common.Body() data: ConsignmentCreateInput
  ): Promise<Consignment> {
    return await this.service.createConsignment({
      data: data,
      select: {
        createdAt: true,
        id: true,
        jobId: true,
        latitude: true,
        longitude: true,
        trackingNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Consignment] })
  @ApiNestedQuery(ConsignmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Consignment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async consignments(@common.Req() request: Request): Promise<Consignment[]> {
    const args = plainToClass(ConsignmentFindManyArgs, request.query);
    return this.service.consignments({
      ...args,
      select: {
        createdAt: true,
        id: true,
        jobId: true,
        latitude: true,
        longitude: true,
        trackingNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Consignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consignment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async consignment(
    @common.Param() params: ConsignmentWhereUniqueInput
  ): Promise<Consignment | null> {
    const result = await this.service.consignment({
      where: params,
      select: {
        createdAt: true,
        id: true,
        jobId: true,
        latitude: true,
        longitude: true,
        trackingNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Consignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consignment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateConsignment(
    @common.Param() params: ConsignmentWhereUniqueInput,
    @common.Body() data: ConsignmentUpdateInput
  ): Promise<Consignment | null> {
    try {
      return await this.service.updateConsignment({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          jobId: true,
          latitude: true,
          longitude: true,
          trackingNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Consignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consignment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteConsignment(
    @common.Param() params: ConsignmentWhereUniqueInput
  ): Promise<Consignment | null> {
    try {
      return await this.service.deleteConsignment({
        where: params,
        select: {
          createdAt: true,
          id: true,
          jobId: true,
          latitude: true,
          longitude: true,
          trackingNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
