/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CourierService } from "../courier.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CourierCreateInput } from "./CourierCreateInput";
import { Courier } from "./Courier";
import { CourierFindManyArgs } from "./CourierFindManyArgs";
import { CourierWhereUniqueInput } from "./CourierWhereUniqueInput";
import { CourierUpdateInput } from "./CourierUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CourierControllerBase {
  constructor(
    protected readonly service: CourierService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Courier })
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCourier(
    @common.Body() data: CourierCreateInput
  ): Promise<Courier> {
    return await this.service.createCourier({
      data: data,
      select: {
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
        userId: true,
        vehicleNumber: true,
        vehicleType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Courier] })
  @ApiNestedQuery(CourierFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async couriers(@common.Req() request: Request): Promise<Courier[]> {
    const args = plainToClass(CourierFindManyArgs, request.query);
    return this.service.couriers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
        userId: true,
        vehicleNumber: true,
        vehicleType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Courier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async courier(
    @common.Param() params: CourierWhereUniqueInput
  ): Promise<Courier | null> {
    const result = await this.service.courier({
      where: params,
      select: {
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
        userId: true,
        vehicleNumber: true,
        vehicleType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Courier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCourier(
    @common.Param() params: CourierWhereUniqueInput,
    @common.Body() data: CourierUpdateInput
  ): Promise<Courier | null> {
    try {
      return await this.service.updateCourier({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          status: true,
          updatedAt: true,
          userId: true,
          vehicleNumber: true,
          vehicleType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Courier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Courier",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCourier(
    @common.Param() params: CourierWhereUniqueInput
  ): Promise<Courier | null> {
    try {
      return await this.service.deleteCourier({
        where: params,
        select: {
          createdAt: true,
          id: true,
          status: true,
          updatedAt: true,
          userId: true,
          vehicleNumber: true,
          vehicleType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
